name = "btc-verified"
version = "0.1.0"
license = "Apache-2.0"
defaultTargets = ["BtcVerified", "Tests"]
testDriver = "tests"
lintDriver = "batteries/runLinter"

[leanOptions]
weak.linter.mathlibStandardSet = true

[[lean_lib]]
name = "BtcVerified"

[[lean_lib]]
name = "Tests"

[[lean_exe]]
name = "tests"
root = "TestsMain"

[[require]]
name = "mathlib"
scope = "leanprover-community"
